// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	TableNumber int32
	Status      string
	OpenedAt    pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrderEvent struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	OrderID     pgtype.UUID
	EventType   string
	Payload     []byte
	OccurredAt  pgtype.Timestamptz
	ProcessedAt pgtype.Timestamptz
}

type OrderItem struct {
	ID        pgtype.UUID
	OrderID   pgtype.UUID
	ProductID string
	Quantity  int32
	Notes     pgtype.Text
	DeletedAt pgtype.Timestamptz
}
