// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderEvents = `-- name: GetOrderEvents :many
SELECT id, tenant_id, order_id, event_type, payload, occurred_at, processed_at FROM order_events 
WHERE order_id = $1 
ORDER BY occurred_at ASC
`

func (q *Queries) GetOrderEvents(ctx context.Context, orderID pgtype.UUID) ([]OrderEvent, error) {
	rows, err := q.db.Query(ctx, getOrderEvents, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderEvent
	for rows.Next() {
		var i OrderEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.EventType,
			&i.Payload,
			&i.OccurredAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrderEvent = `-- name: InsertOrderEvent :exec

INSERT INTO order_events (
    id, tenant_id, order_id, event_type, payload, occurred_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (id) DO NOTHING
`

type InsertOrderEventParams struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	OrderID    pgtype.UUID
	EventType  string
	Payload    []byte
	OccurredAt pgtype.Timestamptz
}

// Arquivo: backend/sql/query.sql
func (q *Queries) InsertOrderEvent(ctx context.Context, arg InsertOrderEventParams) error {
	_, err := q.db.Exec(ctx, insertOrderEvent,
		arg.ID,
		arg.TenantID,
		arg.OrderID,
		arg.EventType,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
